#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

# Modified files, update the modDatetime
git diff --cached --name-status |
grep -i '^M.*\.md$' |
while read _ file; do
  filecontent=$(cat "$file")
  frontmatter=$(echo "$filecontent" | awk -v RS='---' 'NR==2{print}')
  draft=$(echo "$frontmatter" | awk '/^draft: /{print $2}')

  if [ "$draft" = "false" ]; then
    echo "$file modDatetime updated"
    sed -i.bak "/---/,/---/s/^modDatetime:.*$/modDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file"
    git add "$file"
  fi

  if [ "$draft" = "first" ]; then
    echo "First release of $file, draft set to false and modDatetime removed"
    sed -i.bak "/---/,/---/s/^modDatetime:.*$/modDatetime:/" "$file"
    sed -i.bak "/---/,/---/s/^draft:.*$/draft: true/" "$file"
    git add "$file"
  fi
done

# New files, add/update the pubDatetime
git diff --cached --name-status | grep -i "^(A).*\.md$" | while read _ file; do
  sed -i.bak "/---/,/---/s/^pubDatetime:.*$/pubDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file"
  git add "$file"
done
